services: # 各コンテナを定義
  nginx:
    container_name: nginx
    image: nginx:1.28.0
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
  php:
    container_name: php
    ports:
      - 9000:9000
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    tty: true
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    # コンテナ内で使用される環境変数を定義
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  # 名前付きボリュームの作成
  mysqldata: