name: PHPUnit

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
      
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit