name: PHPUnit

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
      
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v4
      with:
        version: "^12.3"
        php_version: 8.3
        configuration: phpunit.xml